version: '3'

services:
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5500:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      # - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ssr_app_db

volumes:
  db-store:
